export interface Message {
  title:string;
  messages:string[];
}

export enum MessageType {
  RACE_CONFIGURATION,
  ATHLETE_REGISTRATION,
  ATHLETE_PARTIAL_REGISTRATION,
  SIMPLE_MESSAGE,
  DOWN,
  VALID_FINISHED_CROSSING,
  NO_VALID_CROSSING,
  ATHLETE_REMOVED,
  UPDATE_CATEGORY,
  CHANGE_CATEGORY_NAME,
  RACE_PERFORMED,
  ACCOUNT,
  RACE_OFF_LINE,
}